server:
  servlet:
    context-path: /middleware
  port: 8087

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# database
  datasource:
    url: jdbc:mysql://localhost:3306/db_middleware?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: db_middleware
# redis
  redis:
    host: 127.0.0.1
    port: 6379
# rabbitmq
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /
    port: 5672
    username: guest
    password: guest
mq:
  env: local
  basic:
    info:
      queue:
        name: ${mq.env}.middleware.mq.basic.info.queue
      exchange:
        name: ${mq.env}.middleware.mq.basic.info.exchange
      routing:
        key:
          name: ${mq.env}.middleware.mq.basic.info.routing.key
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
# sql log
logging:
  level:
    com.debug.middleware.model.mapper: debug
