server:
  servlet:
    context-path: /middleware
  port: 8087

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# database
  datasource:
    url: jdbc:mysql://localhost:3306/db_middleware?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: db_middleware
# redis
  redis:
    host: 127.0.0.1
    port: 6379
# rabbitmq
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /
    port: 5672
    username: guest
    password: guest
mq:
  env: local
# 基本消息模型
  basic:
    info:
      queue:
        name: ${mq.env}.middleware.mq.basic.info.queue
      exchange:
        name: ${mq.env}.middleware.mq.basic.info.exchange
      routing:
        key:
          name: ${mq.env}.middleware.mq.basic.info.routing.key
  # 基本消息模型
  object:
    info:
      queue:
        name: ${mq.env}.middleware.mq.object.info.queue
      exchange:
        name: ${mq.env}.middleware.mq.object.info.exchange
      routing:
        key:
          name: ${mq.env}.middleware.mq.object.info.routing.key
# 消息模型 - fanoutExchange
  fanout:
      queue:
        one:
          name: ${mq.env}.middleware.mq.fanout.one.queue
        two:
          name: ${mq.env}.middleware.mq.fanout.two.queue
      exchange:
        name: ${mq.env}.middleware.mq.fanout.exchange
# 消息模型 - directExchange
  direct:
    queue:
      one:
        name: ${mq.env}.middleware.mq.direct.one.queue
      two:
        name: ${mq.env}.middleware.mq.direct.two.queue
    exchange:
      name: ${mq.env}.middleware.mq.direct.exchange
    routing:
      key:
        one:
          name: ${mq.env}.middleware.mq.direct.routing.key.one
        two:
          name: ${mq.env}.middleware.mq.direct.routing.key.two
# 消息模型 - topicExchange
  topic:
    queue:
      one:
        name: ${mq.env}.middleware.mq.topic.one.queue
      two:
        name: ${mq.env}.middleware.mq.topic.two.queue
    exchange:
      name: ${mq.env}.middleware.mq.topic.exchange
    routing:
      key:
        one:
          name: ${mq.env}.middleware.mq.topic.routing.*.key
        two:
          name: ${mq.env}.middleware.mq.topic.routing.#.key
# 自动确认机制
  auto:
    knowledge:
      queue:
        name: ${mq.env}.middleware.auto.knowledge.queue
      exchange:
        name: ${mq.env}.middleware.auto.knowledge.exchange
      routing:
        key:
          name: ${mq.env}.middleware.auto.knowledge.routing.key
# 手动确认机制
  manual:
    knowledge:
      queue:
        name: ${mq.env}.middleware.manual.knowledge.queue
      exchange:
        name: ${mq.env}.middleware.manual.knowledge.exchange
      routing:
        key:
          name: ${mq.env}.middleware.manual.knowledge.routing.key
  # 死信队列消息模型
  dead:
    queue:
      name: ${mq.env}.middleware.dead.queue
    exchange:
      name: ${mq.env}.middleware.dead.exchange
    routing:
      key:
        name: ${mq.env}.middleware.dead.routing.key
  producer:
    basic:
      exchange:
        name: ${mq.env}.middleware.producer.basic.exchange
      routing:
        key:
          name: ${mq.env}.middleware.producer.basic.routing.key
  consumer:
    real:
      queue:
        name: ${mq.env}.middleware.consumer.real.queue
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
# sql log
logging:
  level:
    com.debug.middleware.model.mapper: debug
